# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
    - image: aravindaw/seleniumx:1.0.0
      name: sleniumx
      environment:
        MAVEN_OPTS: -Xmx3200m


    working_directory: /home/circleci/seleniumx-demo-with-circleCI

    steps:
    - checkout

    - run: sudo su seluser
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run unit tests!
    - run: mvn integration-test

    - store_artifacts:
        path: target/surefire-reports
        destination: tr1

    - store_test_results:
        path: target/surefire-reports