# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 3
jobs:
  build:
    docker:
    - image: aravindaw/seleniumx:1.0
      name: sleniumx
      port: 4444:4444
      environment:
      MAVEN_OPTS: -Xmx3200m

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - run:
        command: |
          sudo apt-get install libxi6 libgconf-2-4
          sudo apt-get -y install xvfb gtk2-engines-pixbuf
          sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
          sudo apt-get install xvfb
          sudo apt-get -y install imagemagick x11-apps

    - run:
        name: Running X virtual framebuffer
        command: Xvfb :0 -ac &

    - run:
        name: Run Tests
        command: |
          export DISPLAY=:99

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run unit tests!
    - run: mvn integration-test