# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 3
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk-stretch

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout
    - run:
        name: Download Selenium server
        command: curl -O http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
    - run:
        name: Download Selenium chrome driver
        command: curl -O https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux32.zip
    - run:
        name: Extract chrome driver
        command: |
          unzip chromedriver_linux64.zip
          chown -R circleci:circleci chromedriver

    - run:
        name: Start Selenium server
        command: java -Dwebdriver.chrome.driver="~/repo/chromedriver" -jar selenium-server-standalone-3.141.59.jar -port 4444
        background: true

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run unit tests!
    - run: mvn integration-test