# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 3
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: selenium/standalone-chrome:latest

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - run:
        name: install maven
        command: |
          sudo apt-get update
          sudo apt install maven -y
          mvn -version

    - run:
        name: Create circleci user
        command: |
          sudo useradd -m circleci
          sudo chown -R seluser:seluser /home/circleci
          ls -la /home

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run unit tests!
    - run: mvn integration-test