# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: aravindaw/seleniumx:1.0
      name: sleniumx
      port: 4444:4444
      environment:
      MAVEN_OPTS: -Xmx3200m

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - run:
        name: Install latest version of ChromeDriver Sample
        command: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install google-chrome-unstable

    - run:
        name: Install latest version of ChromeDriver Sample
        command: |
          sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
          sudo unzip chromedriver_linux64.zip
          sudo rm chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/
          sudo chmod 777 /usr/bin/chromedriver

    - run:
        command: |
          sudo apt-get install libxi6 libgconf-2-4 -y
          sudo apt-get install xvfb gtk2-engines-pixbuf -y
          sudo apt-get install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable -y
          sudo apt-get install xvfb -y
          sudo apt-get install imagemagick x11-apps -y

    - run:
        name: Running X virtual framebuffer
        command: Xvfb :0 -ac &

    - run:
        name: Run Tests
        command: |
          export DISPLAY=:99

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run unit tests!
    - run: mvn integration-test