# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 3
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: selenium/standalone-chrome:latest
    - image: circleci/openjdk:8-jdk-stretch