# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
    - image: seleniumx/standalone-chrome
      user: seluser
      name: sleniumx
      environment:
        MAVEN_OPTS: -Xmx3200m


    working_directory: /home/seluser/seleniumx-demo-with-circleCI

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - run:
        name: Start selenium standalon server
        command: |
          ps -ef | grep selenium
          sudo kill $(ps aux | grep 'selenium' | awk '{print $2}')
          ps -ef | grep selenium
          java -Dwebdriver.chrome.driver="/opt/selenium/chromedriver-78.0.3904.70" -jar /opt/selenium/selenium-server-standalone.jar -port 4444
          ps -ef | grep selenium
        background: true

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run unit tests!
    - run: mvn integration-test

    - store_artifacts:
        path: target/surefire-reports
        destination: tr1

    - store_test_results:
        path: target/surefire-reports